// <auto-generated />
using System;

using GraphQLDotNet.Src.Data;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GraphqlDotNetDemo.Src.Data.Migrations
{
    [DbContext(typeof(StorageContext))]
    [Migration("20210806202158_First-migration")]
    partial class Firstmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("GraphqlDotNetDemo.Src.Data.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2d7e67b5-7226-4db2-a0fb-d6bd89560f98"),
                            Description = "Cash account for our users",
                            OwnerId = new Guid("6f0098f9-8830-4acb-9d3d-f1326a42b2c0"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("91ee174e-8fb2-4c3a-9124-5a7f45180dee"),
                            Description = "Savings account for our users",
                            OwnerId = new Guid("14680de5-ee8a-4101-88ae-945f08edb532"),
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("11576a8d-c47f-4dbc-b17a-e5aa61548ff9"),
                            Description = "Income account for our users",
                            OwnerId = new Guid("14680de5-ee8a-4101-88ae-945f08edb532"),
                            Type = 3
                        });
                });

            modelBuilder.Entity("GraphqlDotNetDemo.Src.Data.Entities.Owner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Owners");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6f0098f9-8830-4acb-9d3d-f1326a42b2c0"),
                            Address = "John Doe's address",
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = new Guid("14680de5-ee8a-4101-88ae-945f08edb532"),
                            Address = "Jane Doe's address",
                            Name = "Jane Doe"
                        });
                });

            modelBuilder.Entity("GraphqlDotNetDemo.Src.Data.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UniqueCode");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8e9147f2-fdf3-4852-8e6d-e00300d6ff23"),
                            Code = "admin",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("0a4ba781-4394-4da7-97e8-afcf0f049907"),
                            Code = "user",
                            Name = "User"
                        });
                });

            modelBuilder.Entity("GraphqlDotNetDemo.Src.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UniqueUserEmail");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0ab8d418-d557-40f6-b7cf-5773f5d9b46a"),
                            Email = "admin@mail.com",
                            Name = "Admin",
                            Password = "123",
                            RoleId = new Guid("8e9147f2-fdf3-4852-8e6d-e00300d6ff23"),
                            Status = 1
                        });
                });

            modelBuilder.Entity("GraphqlDotNetDemo.Src.Data.Entities.Account", b =>
                {
                    b.HasOne("GraphqlDotNetDemo.Src.Data.Entities.Owner", "Owner")
                        .WithMany("Accounts")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("GraphqlDotNetDemo.Src.Data.Entities.User", b =>
                {
                    b.HasOne("GraphqlDotNetDemo.Src.Data.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("GraphqlDotNetDemo.Src.Data.Entities.Owner", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("GraphqlDotNetDemo.Src.Data.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
